credentials:
  usernames:
    saad:
      email: saadelhidaoui@gmail.com
      name: Saad Elhidaoui
      password: '123'
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - test@gmail.com
